Fix git can't create remote branche from remote branch
Need to use the local branch instead

error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'copy-10fa1cbc6cc4-release-v2.16' on the remote side.
- Checking if the <src> being pushed ('refs/remotes/origin/main')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'refs/remotes/origin/main:refs/heads/copy-10fa1cbc6cc4-release-v2.16'?

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>